server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://47.96.97.87:3307/azure?useUnicode=true&serverTimezone=GMT&characterEncoding=utf8&useSSL=true
    username: root
    password: zyb.zyb
  application:
    name: easyExcel_init #将来作为微服务的名称
mybatis:
  type-aliases-package: sx.nine.pojo.User
  mapper-locations: classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true